spring:
  application:
    name: report-service
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: ferhad
    password: Ferhad2002.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8095

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka