spring:
  application:
    name: report-service
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices_jooq
    username: ferhad
    password: Ferhad2002.

server:
  port: 8095

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka