server:
  port: 8088

spring:
  application:
    name: api-gateway

zuul:
  routes:
    auth:
      stripPrefix: false
      serviceId: auth-service
    reports:
      stripPrefix: false
      serviceId: report-service
  host:
    socket-timeout-millis: 30000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

auth-service:
  ribbon:
    listOfServers: http://localhost:9191

report-service:
  ribbon:
    listOfServers: http://localhost:8095

ribbon:
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

management:
  endpoints:
    enabled: true
