server:
  port: 8080

spring:
  application:
    name: api-gateway

zuul:
  routes:
    auth:
      path: /auth/**
      service-id: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
