grpc:
  server:
    port: 9898

server:
  port: 8090

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: ferhad
    password: Ferhad2002.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092
      
eureka:
  client:
    service-url:
      default-zone: http://discoveryservice:8761/eureka

