grpc:
  server:
    port: 9898

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/task
    username: ferhad
    password: Ferhad2002.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      default-zone: http://discoveryservice:8761/eureka
